print("Hello! Please enter the following information: \n")
first_name = input("First name: ")
last_name = input("Last name: ")
email = input("Email address: ")
phone_number = input("Phone number: ")
job_title = input("Job title: ")
id_number = input("ID Number: ")
hair = input("Hair color: ")
eyes = input("Eyes color: ")
month = input("Starting Month: ")
traning = input("Completed additional training? ")

print("\n The ID Card is: ")
print("----------------------- \n")
print(last_name.upper() + ", " + first_name.capitalize() + "\n")
print(job_title.title())
print(id_number + "\n")
print(email.lower())
print(phone_number)
print(f"Hair: {hair:15} Eyes: {eyes}")
print(f"Month: {month:14} Training: {traning}")

print("-----------------------")

